### ISSUE TITLE
Cannot read property 'includeInto' of undefined

### ISSUE THREAD

**Issue by Asteb612** [abe33/atom-tablr#100]
tablr version 1.8.3
atom version 1.27.0 with atom-ide
This message is on the open view.

**Comment by higorhi** [comment]
After updating Atom, Tablr will no longer open Table Editor issuing the same error:
`Cannot read property 'includeInto' of undefined`

Still shows the preview, though, except after selecting Table Editor mode.

![image](https://user-images.githubusercontent.com/23512845/41797629-2e23ffe4-7641-11e8-8263-19458b3749d7.png)

Atom 1.28.0
Tablr 1.8.3

**Comment by TakashiAoki** [comment]
I am also.
I get the same error message.

**Comment by duncdrum** [comment]
same on macOS 10.13.5

**Comment by brundonsmith** [comment]
Same here, Windows 10 Atom 1.28

**Comment by rvsandeep** [comment]
Same here on Ubuntu 18.04

**Comment by syrsly** [comment]
Same here, just submitted a duplicate issue, sorry about that.

**Comment by kguidonimartins** [comment]
Same here on Ubuntu 16.04

**Comment by ludovicriffault** [comment]
Same here with Atom 1.28.0 x64 on macOS High Sierra

**Comment by pjnr1** [comment]
Same here;
Atom 1.28.0
macOS High Sierra 10.13.4
tablr 1.8.3

**Comment by acrenwelge** [comment]
Same here
Atom 1.28.0
Windows 10

**Comment by franiis** [comment]
Same in:
Atom 1.28.1 x64
tablr 1.8.3
Windows 10

**Comment by wataru129** [comment]
Same here
 atom 1.28.0
macOS High Sierra 10.13.4

**Comment by pstaubs** [comment]
Issue persists in atom 1.28.2/tablr 1.83 and essentially renders the package usless.

**Comment by dsananez** [comment]
Same here. Atom 1.28.2 W10. Could someone fix this? ty

**Comment by Semihal** [comment]
Likewise.

**Comment by spettifer-fdb** [comment]
Given there have been no commits for at least a year I'd guess the author is no longer supporting this so unless it turns out to be a core problem in Atom (seems unlikely since more people would be shouting about broken stuff), then it's simply a breaking change in Atom that may or may not get fixed in tablr depending on whether or not the author resurrects it or someone submits a PR or forks it. I'd have a crack but I suspect it's well beyond my javascript skills.

**Comment by calgacus** [comment]
Seems to hit a snag deep in vm.js line 56: 
 ` return realRunInContext.call(this, contextifiedSandbox, options);return realRunInContext.call(this, contextifiedSandbox, options);`   
That return the undefined that gets returned to pool.js around line  66:
 
`const mixin = vm.runInContext(source, context, ${plural}-pool.vm)`
 `mixin.includeInto(this)`   //-- this is where the exception gets thrown.
 

 All those  runInContext APIs are new to me so I doubt I can take this anywhere anytime soon.  Shame, I had just found this package and for a few tests it worked great then I hit this bug and which renders it useless, it could have been very useful.  I really hope it gets fixed.

**Comment by mfripp** [comment]
@calgacus, it looks like I was debugging this at the same time as you (wish I'd seen your comment first, although it might have scared me off!). I just posted a pull request that seems to fix this, at least for me. If you want, you can install it via 

    apm uninstall tablr
    apm install https://github.com/mfripp/atom-tablr.git

I don't intend to do anything more with this fork, but it may help people use this great package until the main code gets fixed.

**Comment by calgacus** [comment]
Thanks! It works for me.

**Comment by tomasztyzaj** [comment]
Thanks @mfripp, worked for me too on MacOS High Sierra 10.13.6 and Atom 1.28.2

**Comment by spettifer-fdb** [comment]
Yep, W10 Atom 1.28.2 working fine. Thanks for the fix!

**Comment by a-paul-taylor** [comment]
Fixed it for me (1.28.2 W7) - thanks!

**Comment by kguidonimartins** [comment]
Thanks, @mfripp! Working fine too on Ubuntu 16.04 and Atom 1.28.1

**Comment by piuccio** [comment]
Seems to be broken again on Atom `1.29.0`

**Comment by spettifer-fdb** [comment]
@piuccio Are you sure you haven't accidentally updated the package? The fork provided by @mfripp will show as being an older version so Atom's package manager will 'update' it to 1.8.3 if you let it and that will overwrite the fix. Until an official release happens, you will need to ignore all updates to tablr if you want it to keep working. I am running Atom 1.29.0 and it is working fine with the fork.

**Comment by piuccio** [comment]
oh cool, sorry I missed the https://github.com/abe33/atom-tablr/issues/100#issuecomment-406904774 about installing from a fork. Yes it works fine now

**Comment by spettifer-fdb** [comment]
@piuccio Great!

**Comment by randy** [comment]
@mfripp, any chance you can also throw in the fix for #93? https://github.com/abe33/atom-tablr/issues/93#issuecomment-347242628

**Comment by puttkraidej** [comment]
work like charm!

**Comment by alanzzhao-toast** [comment]
on macosx. tried the terminal commands, but get 

`Couldn't clone https://github.com/mfripp/atom-tablr.git
`
what am i doing wrong?

**Comment by dschneiderch** [comment]
@alanzzhao-toast  make sure you have git installed and available on your PATH

**Comment by skytreetower** [comment]
@mfripp

I run Atom 1.32.1 for Win10. I installed the ‘tablr’ package and ran into https://github.com/abe33/atom-tablr/issues/100. I searched for ‘atom-tablr’ package in both Atom and on the webpage with no hit. So I uninstalled ‘tablr’, cloned the git repo https://github.com/mfripp/atom-tablr.git and copied the directory structure to the .atom\packages directory. Restarted Atom but the package seems to be not running. I cannot open a single CSV file, also the preferences dialog does not open up. So it seems like the package is not running. What did I do wrong and how can I get it to work?
Once it is working, can I configure Atom in a way that it always opens all CSV files with the same settings? We only have semicolon separated files, and I do not want to configure the settings anew for each file I open.
And is it possible to detect any text file without suffix as CSV as well? All our interface files that we get from partners and send there have no file extension.

**Comment by Palmstroemen** [comment]
> @mfripp
Why not use the installation process as described above? Maybe packages need to be registered somewhere in a config-file of Atom.
Yes to all your questions. Yes you can define the default settings and yes you can define which file-suffix to be opened automatically with the tablr-extension.

**Comment by EvilRenegade** [comment]
> @calgacus, it looks like I was debugging this at the same time as you (wish I'd seen your comment first, although it might have scared me off!). I just posted a pull request that seems to fix this, at least for me. If you want, you can install it via
> 
> ```
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git
> ```
> 
> I don't intend to do anything more with this fork, but it may help people use this great package until the main code gets fixed.

As of 2019-04-19, this is still the solution to get it to work.

**Comment by damianobarbati** [comment]
+1

**Comment by clearzale** [comment]
> @calgacus, it looks like I was debugging this at the same time as you (wish I'd seen your comment first, although it might have scared me off!). I just posted a pull request that seems to fix this, at least for me. If you want, you can install it via
> 
> ```
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git
> ```
> 
> I don't intend to do anything more with this fork, but it may help people use this great package until the main code gets fixed.

Amazing, thx!

**Comment by TSDAdam** [comment]
@skytreetower I had the same issue as you.  I got it working by doing:

- Install standard tablr, the non-working one
- replace the copy of lib\mixins\pool.js in your own .atom folder with the one here > https://github.com/mfripp/atom-tablr/blob/master/lib/mixins/pool.js

That worked for me on windows.

**Comment by philipsimonhall** [comment]
For the record, this also worked for me on Fedora 30 with Atom 1.39.1, just remember to have git installed for installation steps to work, that caught me out temporarily.

**Comment by PaoloC68** [comment]
> ```
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git
> ```
This worked for me too on a Mac.

**Comment by s0q** [comment]
> 
> 
> @skytreetower I had the same issue as you. I got it working by doing:
> 
>     * Install standard tablr, the non-working one
> 
>     * replace the copy of lib\mixins\pool.js in your own .atom folder with the one here > https://github.com/mfripp/atom-tablr/blob/master/lib/mixins/pool.js
> 
> 
> That worked for me on windows.

This also worked for me on windows, excellent work!

**Comment by thebestpol** [comment]
@mfripp Thanks for sharing it works

**Comment by eirerocks** [comment]
@mfripp - thanks that pull request worked for me - don't know what you did but it works!
it would be good if the original author could have a look and update main for latest Atom

**Comment by dev4indglobal** [comment]
@mfripp Thanks, It worked for me

**Comment by darkn3rd** [comment]
Still happening on mine 1.8.3

**Comment by layerssss** [comment]
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git

As of 13 March, 2020, this is still the solution.

**Comment by KLaurence** [comment]
Hello to everyone here! This might not be on topic, but I am trying mfripp's solution for this plugin since it seems to work for others. It doesn't work for me, however, for unknown reasons

When trying to install using `apm install https://github.com/mfripp/atom-tablr.git` or even `apm install mfripp/atom-tablr`, the console says these:

```
Cloning https://github.com/mfripp/atom-tablr.git failed
Installing modules done
Cannot read property 'getReferenceTarget' of null
```

I can't really find a solution for this in the internet regarding Atom, and I might have more luck posting here since it seems to be active and this problem somehow relates to the solution I am trying. Big thanks to everyone that will help me with what to do regarding these.

**Comment by ulysse42** [comment]
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git

Same problem, can confirm this still works

**Comment by maartenderie** [comment]
@abe33 I've you're not going to maintain the project; please find someone who will.

**Comment by arvinyorro** [comment]
> @calgacus, it looks like I was debugging this at the same time as you (wish I'd seen your comment first, although it might have scared me off!). I just posted a pull request that seems to fix this, at least for me. If you want, you can install it via
> 
> ```
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git
> ```
> 
> I don't intend to do anything more with this fork, but it may help people use this great package until the main code gets fixed.

After 2 years, the fix still works

To anyone else who do not know where the pool.js is located, its in 
`C:\Users\{username}\.atom\packages\tablr\lib\mixins`

**Comment by ujLion** [comment]
At: %userprofile%\.atom\packages\tablr\lib\mixins
replace pool.js with https://raw.githubusercontent.com/mfripp/atom-tablr/master/lib/mixins/pool.js
And relaunch

**Comment by BhaveshDiwan** [comment]
> At: %userprofile%.atom\packages\tablr\lib\mixins
> replace pool.js with https://raw.githubusercontent.com/mfripp/atom-tablr/master/lib/mixins/pool.js
> And relaunch

Confirmed to fix the issue in MacOS Catalina 10.15.5

**Comment by ApplyCyber** [comment]
Work for me on Mac. Thank you!!

**Comment by TxJson** [comment]
> At: %userprofile%.atom\packages\tablr\lib\mixins
> replace pool.js with https://raw.githubusercontent.com/mfripp/atom-tablr/master/lib/mixins/pool.js
> And relaunch

Can confirm, this still works on Ubuntu 20.04.

**Comment by Nazareh** [comment]
> @calgacus, it looks like I was debugging this at the same time as you (wish I'd seen your comment first, although it might have scared me off!). I just posted a pull request that seems to fix this, at least for me. If you want, you can install it via
> 
> ```
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git
> ```
> 
> I don't intend to do anything more with this fork, but it may help people use this great package until the main code gets fixed.

that worked for me

**Comment by MattHartzell** [comment]
@mfripp This worked great for me! THANK YOU!

**Comment by johnpitchko** [comment]
https://github.com/abe33/atom-tablr/issues/100?_pjax=%23js-repo-pjax-container#issuecomment-406904774 worked for me, thank you.

**Comment by maxfrischknecht** [comment]
```
apm uninstall tablr
apm install https://github.com/mfripp/atom-tablr.git
```
Still works on February 25, 2021 for Atom 1.54.0, on MacOSx 10.15.7.

**Comment by jberthet** [comment]
```
apm uninstall tablr
apm install https://github.com/mfripp/atom-tablr.git
```

Still work on March 29, 2021 for Atom 1.55.0 on macOS BigSur 11.2.3

Is there any way that this version become available in the package manager so people don't get confused ?

**Comment by ghost** [comment]
> ```
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git
> ```
> 
> Still work on March 29, 2021 for Atom 1.55.0 on macOS BigSur 11.2.3
> 
> Is there any way that this version become available in the package manager so people don't get confused ?

I can confirm this fixes the issue. I'm also on OSX Big Sur (but on 11.3). I'm on Atom 1.57.0 x64.

**Comment by ghost** [comment]
It appears @abe33 does in fact still occasionally contribute to private repositories. Hopefully they'll see this message and someone else can take over the tablr package on apm. What they could do is remove tablr from apm and someone who wants to actively work on tablr could take over the package name. The latest work the owner of this repo did for a private repo is some time this month (May 2021). The hope they see the message and give someone else the ability to take over the package name is the reason why I'm writing this request and tagging them. I wouldn't have written this request if say they hadn't done any work in like 6+ months on Github.

**Comment by gytisrepecka** [comment]
> @skytreetower I had the same issue as you. I got it working by doing:
> 
>     * Install standard tablr, the non-working one
> 
>     * replace the copy of lib\mixins\pool.js in your own .atom folder with the one here > https://github.com/mfripp/atom-tablr/blob/master/lib/mixins/pool.js
> 
> 
> That worked for me on windows.

Thanks, this solution worked 👍

**Comment by inform880** [comment]
@abe33 Can you give one of us rights to this repo to let us take over development?

**Comment by EpicCodeWizard** [comment]
Hey everyone! I made a quick apm package with the updated version. Here it is: [https://atom.io/packages/CSV-Editor](https://atom.io/packages/CSV-Editor)! Here's the apm command: ```apm install CSV-Editor```

**Comment by EpicCodeWizard** [comment]
Hey everyone! I made a quick apm package with the fixed version. Here it is: [https://atom.io/packages/CSV-Editor](https://atom.io/packages/CSV-Editor)! Here's the apm command: ```apm install CSV-Editor```.

**Comment by EpicCodeWizard** [comment]
Hey everyone! I made a quick apm package with the fixed version. Here it is: [https://atom.io/packages/CSV-Editor](https://atom.io/packages/CSV-Editor)! Here's the apm command: ```apm install CSV-Editor``` (I updated the package name so that it is easier to find).

**Comment by claypooj21** [comment]
Just in case, @mfripp's  version can be installed from the atom package installer GUI by typing "mfripp/atom-tablr" into the package search. It still doesn't show up in the search results, but if you're uncomfortable with a terminal (why? I don't know), that's another option.

Thanks @mfripp and @abe33!

**Comment by nitramko** [comment]
> apm install https://github.com/mfripp/atom-tablr.git

**Couldn't clone https://github.com/mfripp/atom-tablr.git**

**Comment by emendir** [comment]
> @calgacus, it looks like I was debugging this at the same time as you (wish I'd seen your comment first, although it might have scared me off!). I just posted a pull request that seems to fix this, at least for me. If you want, you can install it via
> ```
> apm uninstall tablr
> apm install https://github.com/mfripp/atom-tablr.git
> ```
> 

Thanks a tonne!
